GSDRequirements.Web/Controllers/ClassDiagramController.cs
using Microsoft.AspNet.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace GSDRequirements.Web.Controllers
{
    public class ClassDiagramController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

GSDRequirements.Web/Controllers/HomeController.cs
using Microsoft.AspNet.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace GSDRequirements.Web.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

GSDRequirements.Web/Controllers/PackageController.cs
using Microsoft.AspNet.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace GSDRequirements.Web.Controllers
{
    public class PackageController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

GSDRequirements.Web/Controllers/PermissionController.cs
using Microsoft.AspNet.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace GSDRequirements.Web.Controllers
{
    public class PermissionController : Controller
    {
        // GET: /<controller>/
        public IActionResult UserManagement()
        {
            return View();
        }

        // GET: /<controller>/
        public IActionResult ProfileManagement()
        {
            return View();
        }
    }
}

GSDRequirements.Web/Controllers/ProjectController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNet.Mvc;

namespace GSDRequirements.Web.Controllers
{
    public class ProjectController : Controller
    {
        // GET: /<controller>/
        public IActionResult Index()
        {
            return View();
        }
    }
}

GSDRequirements.Web/Controllers/RequirementController.cs
using Microsoft.AspNet.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace GSDRequirements.Web.Controllers
{
    public class RequirementController : Controller
    { 
        // GET: /<controller>/
        public IActionResult Index()
        {
            return View();
        }
    }
}

GSDRequirements.Web/Controllers/UseCaseDiagramController.cs
using Microsoft.AspNet.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace GSDRequirements.Web.Controllers
{
    public class UseCaseDiagramController : Controller
    {
        // GET: /<controller>/
        public IActionResult Index()
        {
            return View();
        }
    }
}

GSDRequirements.Web/Views/ClassDiagram/Index.cshtml
@{ 
    Layout = "_DefaultLayout";
}

<h2>Diagramas de classe</h2>

GSDRequirements.Web/Views/Home/Index.cshtml
@{ 
    Layout = "_DefaultLayout";
}

<h2>Home</h2>

GSDRequirements.Web/Views/Package/Index.cshtml
@{ 
    Layout = "_DefaultLayout";
}

<h2>Gerenciar pacotes</h2>

GSDRequirements.Web/Views/Permission/ProfileManagement.cshtml
@{
    Layout = "_DefaultLayout";
}

<h2>Gerenciar perfis de acesso</h2>

GSDRequirements.Web/Views/Permission/UserManagement.cshtml
@{ 
    Layout = "_DefaultLayout";
}

<h2>Gerenciar usuários do projeto</h2>

GSDRequirements.Web/Views/Project/Index.cshtml
@{ 
    Layout = "_DefaultLayout";
}

<h2>Projetos</h2>

GSDRequirements.Web/Views/Requirement/Index.cshtml
@{
    Layout = "_DefaultLayout";
}

<article data-ng-controller="RequirementsController">
    @Html.Partial("Partial/List")
    @Html.Partial("Partial/Form")
    @Html.Partial("Partial/Details")
    @Html.Partial("Partial/Links")
    @Html.Partial("Partial/Translation")
    @Html.Partial("Partial/NewIssue")
</article>

GSDRequirements.Web/Views/Requirement/Partial/Details.cshtml
<div class="row" data-ng-show="step == 'details'">
    <h2>Detalhes do requisito FR01 - Versão 3</h2>
    <div class="col-md-12">

        <h3>Dados</h3>
        <div class="row margin-top">
            <label class="col-md-1">Descrição</label>
            <div class="col-md-10">Quando o usuário for administrador o sistema deve permitir gerenciar permissões de acesso</div>
        </div>
        <div class="row margin-top">
            <label class="col-md-1">Dificuldade</label>
            <div class="col-md-10">Fácil</div>
        </div>
        <div class="row margin-top">
            <label class="col-md-1">Rank</label>
            <div class="col-md-10">25</div>
        </div>
        <div class="row margin-top">
            <label class="col-md-1">Tipo</label>
            <div class="col-md-10">Requisito funcional</div>
        </div>

        <hr />

        <h3>Vínculos</h3>
        <table class="table table-hover">
            <thead>
                <tr>
                    <th>Item</th>
                    <th>Tipo do item</th>
                    <th>Criador</th>
                    <th>Data</th>
                </tr>
            </thead>
            <tbody>
                <tr data-ng-repeat="link in links">
                    <td>{{link.Item}}</td>
                    <td>{{link.ItemType}}</td>
                    <td>{{link.Creator}}</td>
                    <td>{{link.CreationDate | date:'dd/MM/yyyy'}}</td>
                    <td></td>
                </tr>
            </tbody>
        </table>

        <hr />
        <h3>Versões</h3>
        <table class="table table-hover">
            <thead>
                <tr>
                    <th>Número</th>
                    <th>Criador</th>
                    <th>Data</th>
                </tr>
            </thead>
            <tbody>
                <tr data-ng-repeat="version in versions">
                    <td>{{version.Number}}</td>
                    <td>{{version.Creator}}</td>
                    <td>{{version.CreationDate | date:'dd/MM/yyyy'}}</td>
                    <td>
                        <button class="btn" type="button" title="Ver versão">
                            <span class="glyphicon glyphicon-fullscreen"></span>
                        </button>
                        <button class="btn" type="button" title="Restaurar versão">
                            <span class="glyphicon glyphicon-repeat"></span>
                        </button>
                    </td>
                </tr>
            </tbody>
        </table>

        <button type="button"
                data-ng-click="step = 'list'"
                class="btn btn-default">
            Voltar
        </button>
    </div>
</div>

GSDRequirements.Web/Views/Requirement/Partial/Form.cshtml
<div class="row" data-ng-show="step == 'form'">
    <h2>Adicionar requisito {{requirement.Type.IdPrefix}}03</h2>
    <div class="col-md-12">
        <div class="form-horizontal">
            <div class="form-group">
                <label for="exampleInputName2" class="col-sm-1 control-label">Pacote</label>
                <div class="col-sm-8">
                    <select type="text"
                            class="form-control"
                            data-ng-model="requirement.Package"
                            data-ng-options="package as package.Description for package in packages"></select>
                </div>
            </div>
            <div class="form-group">
                <label for="exampleInputName2" class="col-sm-1 control-label">Condição</label>

                <div class="col-sm-8">
                    <input type="text"
                           class="form-control"
                           data-ng-model="requirement.Condition"
                           placeholder="Quando o usuário for administrador">
                </div>
            </div>
            <div class="form-group">
                <label for="exampleInputName2" class="col-sm-1 control-label">Sujeito</label>
                <div class="col-sm-8">
                    <input type="text"
                           class="form-control"
                           data-ng-model="requirement.Subject"
                           placeholder="o sistema">

                </div>
            </div>
            <div class="form-group">
                <label for="exampleInputName2" class="col-sm-1 control-label">Ação</label>
                <div class="col-sm-8">
                    <input type="text"
                           class="form-control"
                           data-ng-model="requirement.Action"
                           placeholder="deve permitir gerenciar permissões de acesso">
                </div>
            </div>
            <div class="form-group">
                <label for="exampleInputName2" class="col-sm-1 control-label">Dificuldade</label>
                <div class="col-sm-8">
                    <select type="text"
                            class="form-control"
                            data-ng-model="requirement.Difficulty"
                            data-ng-options="difficulty for difficulty in difficultyOptions"></select>
                </div>
            </div>
            <div class="form-group">
                <label for="exampleInputName2" class="col-sm-1 control-label">Rank</label>
                <div class="col-sm-8">
                    <input type="text"
                           class="form-control"
                           data-ng-model="requirement.Rank">
                </div>
            </div>
            <div class="form-group">
                <label for="exampleInputName2" class="col-sm-1 control-label">Tipo</label>
                <div class="col-sm-8">
                    <select type="text"
                            class="form-control"
                            data-ng-model="requirement.Type"
                            data-ng-options="type as type.Label for type in requirementTypeOptions"></select>
                </div>
            </div>
            <div class="btn-group col-sm-offset-1">
                <button type="button" class="btn btn-primary">Salvar</button>
                <button type="button"
                        data-ng-click="step = 'list'"
                        class="btn btn-default">
                    Cancelar
                </button>
            </div>
        </div>
    </div>
</div>

GSDRequirements.Web/Views/Requirement/Partial/Links.cshtml
<div class="row" data-ng-show="step == 'linksList'">
    <h2 class="title-text">Gerenciar vínculos do requisito FR01</h2>
    <h2>
        <button class="btn" data-ng-click="addNewLink();">
            <span class="glyphicon glyphicon-plus-sign"></span> Adicionar vínculo
        </button>
    </h2>

    <div class="col-md-10">
        <table class="table table-hover">
            <thead>
                <tr>
                    <th> Id </th>
                    <th> Tipo </th>
                    <th> Criado por </th>
                    <th> Data de criação</th>
                </tr>
            </thead>
            <tbody>
                <tr data-ng-repeat="link in links">
                    <td>{{link.Item}}</td>
                    <td>{{link.ItemType}}</td>
                    <td>{{link.Creator}}</td>
                    <td>{{link.CreationDate | date:'dd/MM/yyyy'}}</td>
                    <td>
                        <button class="btn" title="Remover vínculo">
                            <span class="glyphicon glyphicon-trash"></span>
                        </button>
                    </td>
                </tr>
            </tbody>
        </table>

        <button type="button"
                data-ng-click="step = 'list'"
                class="btn btn-default">
            Voltar
        </button>
    </div>
</div>

<div class="row" data-ng-show="step == 'addNewLink'">
    <h2>Adicionar vínculo ao requisito FR01</h2>

    <div class="col-md-3">
        <table class="table table-hover">
            <thead>
                <tr>
                    <th> Id </th>
                    <th> Tipo </th>
                </tr>
            </thead>
            <tbody>
                <tr data-ng-repeat="item in specificationItems">
                    <td>{{item.Item}}</td>
                    <td>{{item.ItemType}}</td>
                </tr>
            </tbody>
        </table>

        <button type="button"
                data-ng-click="manageLinks()"
                class="btn btn-default">
            Cancelar
        </button>
    </div>
    <div class="col-md-7">
        ~Dados do artefato~
    </div>
    <div class="col-md-2">
        <button class="btn btn-default">Adicionar</button>
    </div>
</div>

GSDRequirements.Web/Views/Requirement/Partial/List.cshtml
<div class="row" data-ng-show="step == 'list'">
    <h2 class="title-text">Requisitos</h2>
    <h2>
        <button class="btn" data-ng-click="addNewRequiremnt()">
            <span class="glyphicon glyphicon-plus-sign"></span> Adicionar
        </button>
    </h2>

    <div class="col-md-12">
        <table class="table table-hover">
            <thead>
                <tr>
                    <th></th>
                    <th>Id</th>
                    <th> Descrição</th>
                    <th> Pacote</th>
                    <th> Versão</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                <tr data-ng-repeat="r in requirements">
                    <td>
                        <button class="btn btn-default"
                                data-ng-show="r.HasPendingIssues"
                                style="color: red"
                                title="Ver observações pendentes">
                            <span class="glyphicon glyphicon-alert"></span>
                        </button>
                    </td>
                    <td>{{r.Id}}</td>
                    <td>{{r.Description}}</td>
                    <td>{{r.Package.Description}}</td>
                    <td>{{r.Version}}</td>
                    <td>
                        <button class="btn btn-default"
                                type="button"
                                data-ng-click="remove(r)"
                                title="Remover requisito">
                            <span class="glyphicon glyphicon-trash"></span>
                        </button>
                        <button class="btn btn-default"
                                type="button"
                                data-ng-click="addNewVersion(r)"
                                title="Adicionar nova versão">
                            <span class="glyphicon glyphicon-plus"></span>
                        </button>
                        <button class="btn btn-default"
                                type="button"
                                data-ng-click="showDetails(r)"
                                title="Exibir detalhes e gerenciar versões">
                            <span class="glyphicon glyphicon-info-sign"></span>
                        </button>
                        <button class="btn btn-default"
                                type="button"
                                data-ng-click="manageLinks(r)"
                                title="Gerenciar vínculos">
                            <span class="glyphicon glyphicon-transfer"></span>
                        </button>
                        <button class="btn btn-default"
                                type="button"
                                data-ng-click="addIssue(r)"
                                title="Adicionar observação">
                            <span class="glyphicon glyphicon-comment"></span>
                        </button>
                        <button class="btn btn-default"
                                type="button"
                                data-ng-click="addTranslation(r)"
                                title=" Adicionar tradução"
                                data-ng-show="!r.CurrentLanguageAvailable">
                            <span class="glyphicon glyphicon-globe"></span>
                        </button>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
</div>

GSDRequirements.Web/Views/Requirement/Partial/NewIssue.cshtml
<div class="row" data-ng-show="step == 'newIssue'">
    <h2>Adicionar observação em requisito RF01</h2>
    <div class="col-md-6">
        <div class="form-group">
            <label>
                Descrição
                <textarea class="form-control"></textarea>
            </label>
        </div>
        <div class="btn-group">
            <button type="button" class="btn btn-primary">Salvar</button>
            <button type="button"
                    data-ng-click="step = 'list'"
                    class="btn btn-default">
                Cancelar
            </button>
        </div>
    </div>    
</div>

GSDRequirements.Web/Views/Requirement/Partial/Translation.cshtml
<div class="row" data-ng-show="step == 'translation'">
    <h2>Adicionar tradução para requisito FR01</h2>

    <div class="col-md-12">
        <div class="form-horizontal">
            <div class="form-group">
                <span class="col-sm-1">Original:</span>
                <span class="col-sm-11"> When the user is an administrator</span>
            </div>
            <div class="form-group">
                <label for="exampleInputName2" class="col-sm-1 control-label">Condição</label>

                <div class="col-sm-8">
                    <input type="text"
                           class="form-control"
                           data-ng-model="requirement.Condition"
                           placeholder="Quando o usuário for administrador">
                </div>
            </div>

            <hr />

            <div class="form-group">
                <span class="col-sm-1">Original:</span>
                <span class="col-sm-11">  the system</span>
            </div>
            <div class="form-group">
                <label for="exampleInputName2" class="col-sm-1 control-label">Sujeito</label>
                <div class="col-sm-8">
                    <input type="text"
                           class="form-control"
                           data-ng-model="requirement.Subject"
                           placeholder="o sistema">
                </div>
            </div>

            <hr />

            <div class="form-group">
                <span class="col-sm-1">Original:</span>
                <span class="col-sm-11">   must allow access permission management</span>
            </div>
            <div class="form-group">
                <label for="exampleInputName2" class="col-sm-1 control-label">Ação</label>
                <div class="col-sm-8">
                    <input type="text"
                           class="form-control"
                           data-ng-model="requirement.Action"
                           placeholder="deve permitir gerenciar permissões de acesso">
                </div>
            </div>
            <div class="btn-group col-sm-offset-1">
                <button type="button" class="btn btn-primary">Salvar</button>
                <button type="button"
                        data-ng-click="step = 'list'"
                        class="btn btn-default">
                    Cancelar
                </button>
            </div>
        </div>
    </div>
</div>

GSDRequirements.Web/Views/Shared/_DefaultLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/content/vendors.min.css" rel="stylesheet" />
    <link href="~/content/styles.min.css" rel="stylesheet" />
    <script src="~/scripts/vendor.js"></script>
    <script src="~/scripts/app.js"></script>
</head>
<body data-ng-app="app" data-ng-controller="MainController">
    <div class="fluid-container">
        <div class="navbar-header">
            <a class="navbar-brand" href="#">
                <img src="~/content/images/world-logo.gif" height="30px" />
            </a>
        </div>

        <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <li class="active">
                    <a href="@Url.Action("Index","Requirement")">
                        Requisitos <span class="sr-only">(current)</span>
                    </a>
                </li>
                <li>
                    <a href="@Url.Action("Index","UseCaseDiagram")">
                        Casos de uso
                    </a>
                </li>
                <li>
                    <a href="@Url.Action("Index","ClassDiagram")">
                        Diagramas de classe
                    </a>
                </li>
                <li>
                    <a href="@Url.Action("Index","Package")">
                        Pacotes
                    </a>
                </li>
                <li class="dropdown">
                    <a href="#"
                       class="dropdown-toggle"
                       data-toggle="dropdown"
                       role="button"
                       aria-haspopup="true" aria-expanded="false">
                        Acessos <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu">
                        <li><a href="@Url.Action("ProfileManagement", "Permission")">Gerenciar perfis</a></li>
                        <li><a href="@Url.Action("UserManagement", "Permission")">Gerenciar usuário</a></li>
                    </ul>
                </li>
                <li class="dropdown">
                    <a href="#"
                       class="dropdown-toggle"
                       data-toggle="dropdown"
                       role="button"
                       aria-haspopup="true" aria-expanded="false">
                        Relatório <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu">
                        <li><a href="@Url.Action("ProfileManagement", "Permission")">Matriz de rastreabilidade</a></li>
                    </ul>
                </li>
            </ul>

            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a href="@Url.Action("Index", "Project")">
                        Gerenciar Projetos
                    </a>
                </li>
                <li>
                    <div class="navbar-form">
                        <div class="form-group">
                            <label>
                                Projeto atual
                                <select class="form-control">
                                    <option>Projeto X</option>
                                    <option>Projeto Y</option>
                                </select>
                            </label>
                        </div>
                    </div>
                </li>
                <li>
                    <div class="navbar-form">
                        <div class="form-group">
                            <label>
                                Idioma
                                <select class="form-control">
                                    <option>Português</option>
                                    <option>English</option>
                                </select>
                            </label>
                        </div>
                    </div>
                </li>
            </ul>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="container">
                    @RenderBody()
                </div>
            </div>
        </div>
    </div>
</body>
</html>

GSDRequirements.Web/Views/UseCaseDiagram/Index.cshtml
@{ 
    Layout = "_DefaultLayout";
}

<h2>Diagramas de caso de uso</h2>